# Site settings
# Adjust these to reflect your personal information
title:       Kiana Jafari
email:       kjafari@stanford.edu
author:      Kiana
# Update the description to reflect the purpose of your website
description: ""
baseurl:     "" # Leave blank if not hosted in a subdirectory
url:         "https://ikiana.github.io" # Update with your website URL
date_format: "%b %-d, %Y"
header_pages:
  - index.md
  - research.md
  - contact.html

# Google services
google_verification:
# Set Google Analytics ID if you want to track your site
google_analytics: ""
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true # Enable animations for a more dynamic experience
show_related_posts:   true # Show related posts to engage visitors
show_post_footers:    true # Display footers at the end of posts
show_social_icons:    true # Show social media icons to connect
ajaxify_contact_form: true # Use AJAX for a better contact form experience
enable_mathjax: false # Enable if you need MathJax for math equations
extended_fonts: false # Use if you want to load extra fonts
enable_anchorjs: true # Enable for easy linking to headings
post_preview_image: false

# Facebook Page integration
fb_page: false
fb_page_id:

# Disqus post comments
disqus_shortname: "kiana-comments" # Set Disqus to allow post comments, or leave blank to disable

# Facebook Comments plugin
facebook_comments:
facebook_appid:
facebook_comments_number: 5

# Social icons
github_username: ikiana # Update with your GitHub username
#twitter_username: kiana_twitter # Update with your Twitter handle
#linkedin_username: kiana-linkedin # Update with your LinkedIn username
#telegram_username: kiana_telegram # Update with your Telegram username

# Post sharing icons
show_sharing_icons: true # Enable sharing icons to increase reach
# Enable sharing for specific platforms
share_facebook: true
share_twitter: true
share_linkedin: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    linkedin:     'Share on LinkedIn'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting me. I will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
